spring:
  profiles:
    active: localgroup
    group:
      localgroup: localdb, localjpa, common, local
      testgroup: localdb, localjpa, common, test
---
spring:
  config:
    activate:
      on-profile: localdb
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ex23
    username: root
    password: 1234
---
spring:
  config:
    activate:
      on-profile: testdb
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
---
spring:
  config:
    activate:
      on-profile: localjpa
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#        show-sql: true (System.out으로 로그가 출력되어 일반적으로 사용하지 않고 logging으로 처리한다.)
    properties:
      hibernate:
#        show_sql: true (System.out으로 로그가 출력되어 일반적으로 사용하지 않고 logging으로 처리한다.)
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
    open-in-view: false # OSIV와 성능 최적화, off 시 transaction 조욜 전 모든 lazy 로딩을 사용해야 한다.
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j
---
spring:
  config:
    activate:
      on-profile: common
logging:
  level:
    study.datajpa: debug
#  thymeleaf:
#    cache: false
#    prefix: file:./src/main/resources/templates/ # Edit Configurations > Environment > Working Directory: $MODULE_DIR$ \uC124\uC815 \uD544\uC694
#    suffix: .html
#  web:
#    resources:
#      static-locations: "file:./src/main/resources/static/", "classpath:/META-INF/resources/", "classpath:/resources/", "classpath:/static/", "classpath:/public/"
server:
  port: 8080
  tomcat:
    accesslog:
      encoding: UTF-8
---
spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: test