spring:
  profiles:
    active: local
    group:
      local: local-profile
      dev: dev-profile
      production: production-profile
  datasource:
    master:
      jdbcUrl: jdbc:mariadb://localhost:3306/ex31?master=1
      #jdbcUrl: jdbc:mysql://localhost:13306/ex31
      username: root
      password: 1234
    slave:
      jdbcUrl: jdbc:mariadb://localhost:3306/ex31?slave=1
      #jdbcUrl: jdbc:mysql://localhost:23306/ex31
      username: root
      password: 1234
  jpa:
    generate-ddl: false #not used (used spring.jpa.hibernate.ddl-auto=[option])
    open-in-view: false #not used (OSIV)
    show-sql: false #not used (used spring.jpa.properties.hibernate.show_sql)
    hibernate:
      ddl-auto: create-drop
      naming:
        #physical-strategy: study.datajpa.config.datasource.UnderscorePhysicalNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 2000
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
logging:
  charset:
    console: UTF-8
    file: UTF-8
  file:
    path: ./log
    name: ${logging.file.path}/ex31.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
  level:
    #org.hibernate.SQL: debug
    #org.hibernate.type.descriptor.sql: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    #org.springframework.data.auditing.AuditingHandlerSupport: debug
    #org.springframework.jdbc.datasource.DataSourceUtils: debug
    #org.springframework.orm.jpa.JpaTransactionManager: debug
    org.springframework: info
    study.datajpa: debug
---
spring:
  config:
    activate:
      on-profile: local-profile
---
spring:
  config:
    activate:
      on-profile: dev-profile
---
spring:
  config:
    activate:
      on-profile: production-profile
