spring:
  profiles:
    active: localgroup
    group:
      localgroup: localdb, localjpa, localjwt, common, local
      testgroup: localdb, localjpa, localjwt, common, test
---
spring:
  config:
    activate:
      on-profile: localdb
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/jwt
    username: root
    password: 1234
---
spring:
  config:
    activate:
      on-profile: localjpa
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#        show-sql: true (using System.out)
    properties:
      hibernate:
#        show_sql: true (using System.out)
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
    open-in-view: false # OSIV(Open Session In View)
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j
---
spring:
  config:
    activate:
      on-profile: localjwt
jwt:
  header: Authorization
  secret: BfDLA9O40f8EBQiPOPYqOVK6rnWTfFPm8b31CcyhIQvi4rQ454ASNFadlXUgXkR85wJMZ0JhTxFErTASBQ4PUUAt6fwdEzvJLOVgKbPnkhD4nkK7ioGOhVSk1D2Fdy3P # length 128
  token-validity-in-seconds: 86400000 # 86400000 = 1000*60*60*24 = one day
---
spring:
  config:
    activate:
      on-profile: common
logging:
  level:
    example.jwt: debug
server:
  port: 8080
  tomcat:
    accesslog:
      encoding: UTF-8
---
spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: test