version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: take0415/hellopy:0.0.1
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1" # 10%
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80" # local port : container port
    networks:
      - webnet
networks:
  webnet: # which is a load-balanced overlay network